# Generated by Django 4.0.5 on 2022-06-20 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content_html',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_md',
        ),
        migrations.RemoveField(
            model_name='post',
            name='pv',
        ),
        migrations.RemoveField(
            model_name='post',
            name='uv',
        ),
    ]
